version: '3.1'

services:
  boilerplate-app:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      container_name: boilerplate-app
      hostname: boilerplate-app
      restart: always
      ports:
        - 80:80
      volumes:
        - .:/var/www/html
        - ~/.ssh:/root/.ssh
        - ~/.gitconfig:/root/.gitconfig
      environment:
        - DB_HOST=boilerplate-db
        - DB_DATABSE=boilerplate
        - DB_USERNAME=root
        - DB_PASSWORD=password
      depends_on:
        - boilerplate-db

  boilerplate-db:
    image: mysql:5.7
    container_name: boilerplate-db
    hostname: boilerplate-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boilerplate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - .docker/config/mysql.conf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  default:
